version: '3.9'

services:
  minio:
    container_name: media-convert-app-minio
    image: minio/minio:latest
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    command: server --console-address ":9001" /data

  rabbitmq:
    container_name: media-convert-app-rabbitmq
    image: rabbitmq:3.10.7-management
    ports:
      - '15672:15672'
      - '5672:5672'
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
